#module Bruker

export readBrukerFID

function readBrukerFID(f::IOStream; format=Float64)
  data = Array{format,1}([])
  while !eof(f)
    append!(data,(read(f,format)));
  end
  return data[1:2:end]+im*data[2:2:end]
end

"""
`Bruker.readBrukerFID(s::String; format=Float64)` reads a Bruker fid or ser file and returns
the data contained in it as a complex array. For files generated by TopSpin 4.0 and
higher, the default format (`Float64`) will work. For TopSpin 2.0, use
`format=Int32`.
"""
function readBrukerFID(s::String;opts...)
    f=open(s,"r")
    fid=readBrukerFID(f;opts...)
    close(f)
    return fid
end

#end
